# -*- coding: utf-8 -*-
{
    "name": "College ERP",
    "version": "18.0.1.0.0",
    "author": "Mohamad Abbas",
    "category": "Education",
    "summary": "Comprehensive ERP solution for University Management",
    "website": "https://github.com/mohamadabbas963/odoo19-college-erp",
    "sequence": 1,
    "depends": [
        "base",
        "mail",
        "product",
        "account",
    ],
    "data": [
        "security/college_erp_security.xml",
        "security/ir.model.access.csv",
        "data/ir.sequence.csv",
        "views/college_department_views.xml",
        "views/college_course_views.xml",
        "views/college_attendance_views.xml",
        "views/college_exam_result_views.xml",
        "views/college_fees_views.xml",
        "views/college_fee_type_views.xml",
        "views/college_certificate_views.xml",
        "views/college_appointment_views.xml",
        "views/account_move_views.xml",
        "views/college_classroom_view.xml",
        "views/college_erp_teacher_views.xml",
        "views/college_course_registration_views.xml",
        "views/college_student_views.xml",
        "views/college_student_kanban.xml",
        "views/college_student_actions.xml",
        "views/college_student_smart_buttons.xml",
        "reports/college_exam_report.xml",
        "reports/college_payment_report.xml",
        "views/college_erp_menus.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "college_erp/static/src/xml/student_dashboard.xml",
            "college_erp/static/src/js/student_dashboard.js",
        ],
    },
    "application": True,
    "installable": True,
    "license": "LGPL-3",
}